<?php
$json = '[ 
   { 
      "onsite":true,
      "finish":"2019-11-15T15:00:00+00:00",
      "description":"",
      "weight":0.00,
      "title":"Dragon CTF 2019",
      "url":"https://ctf.dragonsector.pl/",
      "is_votable_now":false,
      "restrictions":"Open",
      "format":"Jeopardy",
      "start":"2019-11-14T09:00:00+00:00",
      "participants":10,
      "ctftime_url":"https://ctftime.org/event/887/",
      "location":"Warsaw, Poland",
      "live_feed":"",
      "public_votable":true,
      "logo":"",
      "format_id":1,
      "id":887,
      "ctf_id":103
   },
   { 
      "onsite":false,
      "finish":"2019-11-17T17:00:00+00:00",
      "description":"",
      "weight":0.00,
      "title":"ASIS CTF Finals 2019",
      "url":"https://asisctf.com/",
      "is_votable_now":false,
      "restrictions":"Open",
      "format":"Jeopardy",
      "start":"2019-11-15T17:00:00+00:00",
      "participants":38,
      "ctftime_url":"https://ctftime.org/event/805/",
      "location":"",
      "live_feed":"https://ctftime.org/live/805/",
      "public_votable":true,
      "logo":"https://ctftime.org/media/events/asis_log_gb_2.png",
      "format_id":1,
      "id":805,
      "ctf_id":59
   },
   { 
      "onsite":false,
      "finish":"2019-11-18T05:00:00+00:00",
      "description":"RITSEC CTF 2019 is a security-focused competition that features the following categories: Bin, PWN, Crypto, Forensics, Steganography, and Web.  We welcome beginners and more advanced security friends! There will be three brackets: RIT students, other college students, and everyone else. ",
      "weight":0.00,
      "title":"RITSEC CTF 2019",
      "url":"https://ctf.ritsec.club/",
      "is_votable_now":false,
      "restrictions":"Open",
      "format":"Jeopardy",
      "start":"2019-11-15T17:00:00+00:00",
      "participants":46,
      "ctftime_url":"https://ctftime.org/event/898/",
      "location":"",
      "live_feed":"https://ctftime.org/live/898/",
      "public_votable":true,
      "logo":"https://ctftime.org/media/events/RITSEC_CTF_19_LOGO_1.png",
      "format_id":1,
      "id":898,
      "ctf_id":170
   },
   { 
      "onsite":true,
      "finish":"2019-11-16T06:30:00+00:00",
      "description":"GreHack CTF is Jeopardy style and will be held onsite of the 7th edition of GreHack conference organized by Securimag team.\r\nPlease note that exact start and end time of this event could vary a bit.",
      "weight":0.00,
      "title":"GreHack CTF 2019",
      "url":"https://grehack.fr/2019/",
      "is_votable_now":false,
      "restrictions":"Open",
      "format":"Jeopardy",
      "start":"2019-11-15T22:00:00+00:00",
      "participants":3,
      "ctftime_url":"https://ctftime.org/event/922/",
      "location":"Grenoble, France",
      "live_feed":"",
      "public_votable":true,
      "logo":"",
      "format_id":1,
      "id":922,
      "ctf_id":42
   },
   { 
      "onsite":false,
      "finish":"2019-11-23T19:00:00+00:00",
      "description":"International online challenge\r\nin information security. Good choice to start playing A/D, because we are providing vulnbox in our cloud, so you dont need to be an administrator. Also good choice for pros \u2014\u00a0you will battle with teams from all over the world!",
      "weight":0.00,
      "title":"RuCTFE 2019",
      "url":"https://ructfe.org/",
      "is_votable_now":false,
      "restrictions":"Open",
      "format":"Attack-Defense",
      "start":"2019-11-23T10:00:00+00:00",
      "participants":24,
      "ctftime_url":"https://ctftime.org/event/906/",
      "location":"",
      "live_feed":"",
      "public_votable":true,
      "logo":"https://ctftime.org/media/events/social.png",
      "format_id":2,
      "id":906,
      "ctf_id":6
   }
]'
?>